{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: support-ypay-tls
  labels:
    app: {{ template "support-ypay.name" . }}
    chart: {{ template "support-ypay.chart" . }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
 tls.crt: {{ .Values.secret.data.tls.crt }}
 tls.key: {{ .Values.secret.data.tls.key }} 
{{- end }}